version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/backend"
    open-pull-requests-limit: 20
    schedule:
      interval: "daily"
    commit-message:
      prefix: "DEV: "
  - package-ecosystem: "npm"
    directory: "/frontend-html"
    open-pull-requests-limit: 20
    schedule:
      interval: "daily"
    commit-message:
      prefix: "DEV: "
  - package-ecosystem: "npm"
    directory: "/architect-html"
    open-pull-requests-limit: 20
    schedule:
      interval: "daily"
    commit-message:
      prefix: "DEV: "
    ignore:
      - dependency-name: "eslint"
        versions: [">=10.0.0 <10.1.0"]
  - package-ecosystem: "npm"
    directory: "/chat-html"
    open-pull-requests-limit: 20
    schedule:
      interval: "daily"
    commit-message:
      prefix: "DEV: "
