# For most projects, this workflow file will not need changing; you simply need
# to commit it to your repository.
#
# You may wish to alter this file to override the set of languages analyzed,
# or to provide custom queries or build logic.
#
# ******** NOTE ********
# We have attempted to detect the languages in your repository. Please check
# the `language` matrix defined below to confirm you have the correct set of
# supported CodeQL languages.
#
name: "RunTests"

on:
  push:
    branches: [ master, 20*,testenviroment ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master, 20* ]

jobs:

  frontend:
    name: frontend
    runs-on: windows-2019
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'csharp']
        node-version: [12.x]
        
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: setup node
      uses: actions/setup-node@v2
      with:
       node-version: '12'
     
    - name: Install Yarn
      run: npm install -g yarn
      
    - name: Build Frontend
      run: |
        cd frontend-html
        yarn -version
        node --version
        yarn
        yarn build

    - name: Upload frontend artefact
      uses: actions/upload-artifact@v2
      with:
        name: htmlfrontendbuild
        path: "frontend-html/build"   

    
  analyze:
    needs: frontend
    name: Analyze
    runs-on: windows-2022
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'csharp']
        # CodeQL supports [ 'cpp', 'csharp', 'go', 'java', 'javascript', 'python' ]
        # Learn more:
        # https://docs.github.com/en/free-pro-team@latest/github/finding-security-vulnerabilities-and-errors-in-your-code/configuring-code-scanning#changing-the-languages-that-are-analyzed

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1

    - name: Build Html Server
      run: |
       cd backend
       msbuild Origam.sln -t:restore /p:Configuration="Release Server"
       msbuild Origam.sln -t:build /p:Configuration="Release Server" /t:Server\Origam_Server:Publish -v:m
       
    - name: Upload server artefact
      uses: actions/upload-artifact@v2
      with:
        name: htmlserverbuild
        path: "backend/Origam.Server/bin/Release/net6.0/publish"
        
  compose:
    needs: analyze
    name: Compose
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'csharp']
        
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download HTML5 artefact
      uses: actions/download-artifact@v2
      with:
        name: htmlserverbuild
        path: test/HTML5
        
    - name: Download Frontend artefact
      uses: actions/download-artifact@v2
      with:
        name: htmlfrontendbuild
        path: test/HTML5/clients/origam
        
    - name: Copy model to test directory
      run: |
        mkdir test/model
        cp -r model-tests test/model
        
    - name: Copy Commandline.dll
      run: cp backend/EnterpriseLibrary/CommandLine.dll test/HTML5
        
    - name: Start containers
      run: |
        cd test
        docker-compose --env-file envFile.env -f "docker-compose.yml" --profile test up --abort-on-container-exit 

    - name: Stop containers
      if: always()
      run: |
        cd test
        docker-compose --env-file envFile.env -f "docker-compose.yml" --profile test down

